### ISSUE TITLE
Build vignettes in install()

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1578]
This should be the default behaviour, once the package installation code has moved to remotes. That way remotes focusses on fast installation and devtools on more accurate simulation of install from CRAN.

**Comment by AmundsenJunior** [comment]
Looking into this, is there an idea as to how to change default behavior of `build_vignettes()` with its call to `install()`? 

`build_vignettes()` has `install = TRUE` for a param and its default. If the default of `install()` is changed to `build_vignettes = TRUE` per this feature request, then calling `build_vignettes()` would actually build the vignettes twice.

Do I have that logic correct? Would we want `build_vignettes()` to call install as `devtools::install(..., build_vignettes = FALSE)` to keep the process the same for that function?

**Comment by jimhester** [comment]
@hadley was saying to build vignettes with the `install_*()` functions by default. So that calling `devtools::install_github("repo/xyz")` will build them by default.

Now that remotes has support for building packages this should be a matter of calling the remotes functions with `remotes::install_github(..., build = TRUE, build_opts = c("--no-resave-data", "--no-manual")` (removing the `--no-build-vignettes`) option which is the default.

I am somewhat undecided if this is worth doing now, it will make maintenance more of a burden.

**Comment by DataStrategist** [comment]
So it's clear to me that if I have a package on github (not yet on CRAN), and used `use_vignettes()` and want to let users to see the vignette when they install from github, we should instruct to 
 use `devtools::install_github(..., build_vignettes = TRUE)`. 

However, this prevents me from displaying my vignette on github _per se_. The vignette is (kind of by definition) the best way to explain how to use my package and would like to be able to display it to prospective downloaders on github itself. So I have 2 questions:

 1. What is the motivation for  `.gitignore`ing the `inst/doc`? 
 2. How frowny would it be for me to manually remove `inst/doc` from `gitignore` so that I can show my vignette from github? Would that screw up `install_github()`?

**Comment by hadley** [comment]
@DataStrategist  If you want to display live vignettes, the best solution (IMO) is pkgdown. You are welcome to try something else based on _not_ ignoring `inst/doc`, but you're on your own.

**Comment by DataStrategist** [comment]
@hadley So I guess the question (and this is def. a soft question) then becomes "what's the difference between walthroughing your package in `pkgdown` or in a `vignette`? Is it appropriate to one walkthrough that takes both forms?

**Comment by hadley** [comment]
@DataStrategist pkgdown turns your vignettes into a website

**Comment by DataStrategist** [comment]
@hadley so it does. I'm going to go into the corner and curl into a ball and cry myself to sleep now... thanks.

**Comment by hadley** [comment]
I think we're now unlikely to do this, or if we do, it'll be as a general re-thinking of how we handle vignettes.
