### ISSUE TITLE
feature request: R CMD check and no visible binding for global variable

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1714]
Hi,

I know that the issue of `R CMD check` and the copious amounts of `no visible binding for global variable [variable name]` NOTES it produces has been raised in other forums (e.g., on StackOverflow: https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when, or in the context of other packages: https://github.com/tidyverse/magrittr/issues/29), but the solutions provided therein are either not satisfactory or are actually problematic to the package since the solutions themselves introduce some additional notes/warnings, especially if this is your first time developing package and you are encountering this problem for the first time. 

So I was wondering if the future release of `devtools` can have some routines that automatically take the necessary steps to remove this particular breed of NOTES (e.g., automatically adding necessary variables via `globalVariables(c(...))` or setting them to `NULL`, etc.) since it seems like a very common problem that people encounter and is frustrating to get rid off.

**Comment by jimhester** [comment]
`utils::globalVariables()` is the correct solution to the problem and doesn't introduce any additional issues.

I don't like the idea of providing a helper because there are plenty of cases where this check _does_ catch an issue (a typo in a variable name for instance, or forgetting to include a variable as a function argument), so I think this is something a human needs to look at and verify they are really false positives.

It is possible there could be a [usethis](https://github.com/r-lib/usethis) helper which would help construct the `globalVariables()` call for you but it would be somewhat tricky to do correctly. I think if this was anywhere it would be there rather than in devtools.

**Comment by IndrajeetPatil** [comment]
Okay, gotcha! I will stick to the `utils::globalVariables()` solution then.

So, just to confirm, I should set all variables flagged by `R CMD check` using `utils::globalVariables()` in  `.R` file where the variables are used _before_ the `roxygen` skeleton is specified, right?
