### ISSUE TITLE
track install_github() installs?

### ISSUE THREAD

**Issue by cklunch** [r-lib/devtools#1729]
Is it possible to monitor or count the number of times a package has been installed via install_github()? I'm looking for equivalent numbers to the CRAN logs, but for packages that are only on GitHub. Thanks!

**Comment by jimhester** [comment]
The only way to do this would be to have devtools send a anonymized tracking request to something like google analytics, like what is done with homebrew by default.

We have so far avoided doing this due to privacy concerns, but if there was community support for it we could add it to devtools (with the ability to opt out).

**Comment by cklunch** [comment]
Thanks for the reply! It's good to know it's at least possible. I think this would be a really useful addition to the package, if the community is comfortable with it.

**Comment by dracodoc** [comment]
@cklunch @jimhester 
I think you can use the [tar.gz download count from github API](https://help.github.com/articles/getting-the-download-count-for-your-releases/) for this, since `install_github` always use github api to download the tar.gz first. Something like [this](https://github.com/libgit2/libgit2/downloads).

See [related discussion here](https://stackoverflow.com/questions/6198194/how-to-see-count-of-project-downloads-on-github).

This can be done totally in your side (nothing relate to devtools). You probably can use [the `gh` package](https://github.com/r-lib/gh).

**Comment by jimhester** [comment]
That only works for releases, typically when people use `install_github()` they are installing the current master, not a release.

**Comment by dracodoc** [comment]
Yes I realized that and edited my post. I probably should edit again to make it more obvious to avoid confusions.

**Comment by llrs** [comment]
How would it handle reinstalling a package from the same IP? Who would store the data? How would it handle the GDPR law?

PS:
<blockquote class="twitter-tweet" data-lang="es"><p lang="en" dir="ltr">What would be your opinion on <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> devtools tracking package installations for github (and other) remotes?<br><br>They would be anonymized download counts per package and could be disabled by setting an environment variable. (Suggested by <a href="https://t.co/02U9crxbsm">https://t.co/02U9crxbsm</a>)</p>&mdash; Jim Hester (@jimhester_) <a href="https://twitter.com/jimhester_/status/1019309325150556160?ref_src=twsrc%5Etfw">17 de julio de 2018</a></blockquote>

**Comment by MarkEdmondson1234** [comment]
There would be no concern for GDPR if no ID is stored that can be linked back to a user (I've done GDPR audits for web analytics past few months)  

I've wondered about doing this myself for tracking package installs, which I suggest if using Google Analytics would be best done by a [measurement protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) hit that I've wrapped in https://github.com/MarkEdmondson1234/googleMeasureR - if its a random cid (cookieID) and anonymise ip you would just get aggregated metrics.  Lots of similar services out there that work via a API hit.  I would favour an opt-in though upon installation. ("I agree to give anonymous statistics to help the developers etc. etc")

**Comment by jimhester** [comment]
Thanks @MarkEdmondson1234, that is useful information. [homebrew's analytics](https://docs.brew.sh/Analytics) is a useful model for this and I believe they use that same GA protocol.

**Comment by jimhester** [comment]
This seems unlikely to happen due to CRAN policy / likely community pushback.

**Comment by bakaburg1** [comment]
Hello, I know that the issue is closed (even I didn't understand the CRAN policy problem), but I was wondering if it's possible to check the downloads via github directly, without any action from the R side. Is there any github action or API that can be used for this? Using https://img.shields.io/github/downloads/User/Repo/total.svg doesn't work because it checks only releases downloads.
What actions is actually devtools performing when installing from github? (I tried to check install_github code, but it's very nested and got lost)

**Comment by dracodoc** [comment]
As said before probably only releases download can be checked. 

devtools code about installing were organized in [remotes](https://github.com/r-lib/remotes), you can read it there. I think it just download the source zip from github.

**Comment by MarkEdmondson1234** [comment]
@bakaburg1 In GitHub settings you can see the Insights tabs which tracks the number of clones that I guess correspond to `install_github()` installs (?)

**Comment by jimhester** [comment]
`install_github()` does not clone the repository, it downloads the tar.gz, which GitHub does not track. If there was a way to track this through GitHub we would be doing it.

**Comment by jimhester** [comment]
As this is quite an old issue I am going to lock it, thank you all for the feedback!
