### ISSUE TITLE
devtools not producing some NOTES or WARNINGS

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1811]
I am using devtools `1.13.6` on a Windows 10 machine. It has happened to me multiple times now where I run `devtools::check()` and some `rhub` checks, get `0 Errors | 0 Warnings | 0 Notes`, and then submit to CRAN and get either warnings or notes that I hadn't seen before and have my package rejected:

For example-
1. Bad URLs (not found with `devtools`, but spotted by CRAN's `R CMD CHECK`)
```
Found the following (possibly) invalid URLs:
  URL: https://indrajeetpatil.github.io/ggstatsplot/articles/ggspiestats.html
    From: inst/doc/ggcoefstats.html
    Status: 404
    Message: Not Found
```

2. Unused dependencies (not found by `devtools`, but by `rhub`)

![image](https://user-images.githubusercontent.com/11330453/42323235-71edb684-802d-11e8-8fa3-440a02c1323d.png)

3. Avoiding running spell check test on CRAN servers
https://github.com/r-lib/usethis/issues/408

Am I doing something wrong? Are there some other checks I should be running with `devtools`, in addition to `devtools::check()` and `devtools::check_win_devel()` that can help me catch errors like these?

**Comment by jimhester** [comment]
`devtools::check()` by default does not run the 'version' or 'incoming' checks, because they take a while to run and have to check CRANs or other external servers. You can run them by passing `devtools::check(check_version = TRUE)`

`devtools::check_win_devel()` runs on win-builder, which is an identical setup to the CRANs autocheck makines, so it will give you the same results as what you would get when submitting to CRAN.

**Comment by jimhester** [comment]
It is possible this could be better documented, or the argument could be renamed to make it more clear which tests are suppressed.
