### ISSUE TITLE
Package Installation without .rmd files

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1888]
@jimhester  I've never encountered this issue before (https://github.com/IndrajeetPatil/ggstatsplot/issues/75) and not sure how to do this, so wanted to see if you can suggest some solution.

**Comment by jimhester** [comment]
No there is no solution I am aware of, but based on the error message they are trying to execute the Rmd file directly, which is clearly wrong, I think they may be confused on what the issue is.

Also this question would be better posed to https://community.rstudio.com. (there is a section devoted to package development https://community.rstudio.com/c/package-development)

The devtools issue tracker is for bugs or feature requests for devtools.
