### ISSUE TITLE
'sessioninfo' is not in Suggests: for 'devtools'

### ISSUE THREAD

**Issue by helix123** [r-lib/devtools#1951]
Trying to run a simple `devtools::revdep_check()` with devtools 2.0.1 from CRAN erros (see below).

(I know `revdep_check() is deprecated but pkg `revdepcheck` is not on CRAN yet, see #1910 - rather unfortunate.)

```
--------------------------------------------------------------------------------
Warning: 'function (pkgs, libpath = file.path(tempdir(), "R-lib"), srcpath = libpath, check_libpath = libpath, bioconductor = FALSE, type = getOption("pkgType"), threads = getOption("Ncpus", 1), check_dir = tempfile("check_cran"), install_dir = tempfile("check_cran_install"), env_vars = NULL, quiet_check = TRUE) 
{
    .Deprecated("revdepcheck::revdep_check()", package = "devtools")
}' is deprecated.
Use 'revdepcheck::revdep_check()' instead.
See help("Deprecated") and help("devtools-deprecated").
-- Saving check results to `revdep/checks.rds` ---------------------------------
Error: 'sessioninfo' is not in Suggests: for 'devtools'
```

**Comment by bastistician** [comment]
I just stumbled upon the same error, checked the underlying code, and came to the conclusion that reverse dependency checks are actually "*defunct*" rather than "*deprecated*" in current **devtools**.

Here is why:
```
── Saving check results to `revdep/checks.rds` ─────────────────────────────────
Error: 'sessioninfo' is not in Suggests: for 'devtools'
```
has the following `traceback()`:
```
7: stop("'", package, "' is not in Suggests: for '", pkg_name(path), 
       "'", call. = FALSE)
6: suggests_dep(package, path = path)
5: pkgload::check_suggested(package = package, version = version, 
       compare = compare, path = path)
4: check_suggested("sessioninfo")
3: revdep_check_save(pkg, cache$revdeps, cache$check_dir, cache$libpath)
2: revdep_check_from_cache(pkg, cache)
1: devtools::revdep_check(threads = 3)
```

I thought this would be easy to fix, since we would only need to remove the [obsolete](https://github.com/r-lib/devtools/commit/9785b3a0b57a94ed1ac3a3b7c2d839a044537e4b) call
https://github.com/r-lib/devtools/blob/e4e57aa6a775ef6f48eebc933ed7c4ad0a6e9c07/R/revdep.R#L253
in `revdep_check_save()`.

Unfortunately, this won't revive reverse dependency checks in **devtools** because:

1. the subsequent call
https://github.com/r-lib/devtools/blob/e4e57aa6a775ef6f48eebc933ed7c4ad0a6e9c07/R/revdep.R#L265
fails because of the obsolete argument `libpath`. (This is easy to fix.)

2. most importantly, the workhorse function [`check_cran()`](https://github.com/r-lib/devtools/blob/e4e57aa6a775ef6f48eebc933ed7c4ad0a6e9c07/R/check-cran.R), which should actually run R CMD check on reverse dependencies, no longer does anything in current **devtools** except issuing a deprecation warning (suggesting the use of `revdepcheck::revdep_check()`).

So reverse dependency checks are actually "defunct" in current **devtools**.

I think this issue could be marked as "won't fix*. Maybe **devtools**`::revdep_check()` will be modified to call **revdepcheck** in the future (maybe once that package is released on CRAN).

**Comment by jimhester** [comment]
`revdep_check()` has been removed. Eventually the revdepcheck package will be on CRAN (or you could use it on GitHub as we do). Or you could try using the unexported functions for reverse dependency checking in the tools package.
