### ISSUE TITLE
Could devtools::release() check for package name availability?

### ISSUE THREAD

**Issue by njtierney** [r-lib/devtools#2081]
Perhaps as part of the series of checks using `release()`, it could check if the package name is available, using `available::available()` from the [available package](https://github.com/ropenscilabs/available)

Also see: https://github.com/r-lib/usethis/issues/808

**Comment by hadley** [comment]
Since `release()` is basically superseded in favour of `use_release_issue()` this really ping pongs back over to usethis; but as I commented in the issue of there, I think we probably don't have any function that's called at the right time, and anyway, if you're thinking of submitting to CRAN, you'll be thinking about a unique name.
