### ISSUE TITLE
Problem with IDE rstudio and Package using devtools

### ISSUE THREAD

**Issue by Cervangirard** [r-lib/devtools#2083]
Hi,

If I try to create new project with Package using Devtools in Rstudio IDE, i got a error 
` R code execution error`
With this output of the console
```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  objet 'create' introuvable
```
The function create doesn't exit anymore in devtools, add something with usethis ?

**Comment by jennybc** [comment]
I can reproduce this RStudio v1.2.1555 (current preview, at the time of writing). It should be an issue on https://github.com/rstudio/rstudio/issues, though. If you want me to open it, @Cervangirard, just let me know. Otherwise, you should describe what you're seeing with *File > New Project... > New Directory > R Package using devtools*. Yes, `devtools::create()` no longer exists and is replaced by `usethis::create_package()`.

**Comment by Cervangirard** [comment]
Thank you.

I have just opened the following issue:

https://github.com/rstudio/rstudio/issues/5152
