### ISSUE TITLE
suggestion: error message recommending `remotes::install_*` when `devtools::install_*` fails?

### ISSUE THREAD

**Issue by ajdamico** [r-lib/devtools#2147]
hi, thanks for the excellent software.

the problem described below doesn't occur with `remotes::install_github` since it has fewer dependencies, one of the benefits of the https://github.com/r-lib/devtools#conscious-uncoupling

`devtools::install_*` has been the standard way to load packages from repos like github, i'm probably not the only user who didn't realize they should switch to `remotes::install_*`

in the event of an install_* error, does it make sense for the error message to encourage users to switch to `remotes::install_*` which doesn't have the same dependency conflicts?

thanks very much for your time  :-)

	install.packages('devtools')

	# # close console and re-open

	# old version of some package on local machine
	packageurl <- "http://cran.r-project.org/src/contrib/Archive/rlang/rlang_0.4.0.tar.gz"
	install.packages(packageurl, repos=NULL, type="source")

	# # close console and re-open

	# fails because running a devtools function loads the rlang library
	devtools::install_github("tidyverse/ggplot2",dependencies = TRUE)

	# Error: .onLoad failed in loadNamespace() for 'pkgload', details:
	  # call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
	  # error: namespace ‘rlang’ 0.4.0 is already loaded, but >= 0.4.1 is required

	# # close console and re-open

	# fails because `rlang` is required by devtools, but it doesn't have the same >= 0.4.1 as ggplot2
	# this step updates dependencies ggplot2 shares with devtools
	install.packages( "devtools" , dependencies = TRUE )
	devtools::install_github("tidyverse/ggplot2" , dependencies = TRUE )

	# # close console and re-open

	# update the problem packages by hand
	install.packages( c( "rlang" , "processx" ) , dependencies = TRUE )
	devtools::install_github("tidyverse/ggplot2" , dependencies = TRUE )
	# works

**Comment by krlmlr** [comment]
Problem occurred in https://github.com/tidyverse/dplyr/issues/5016.

**Comment by jimhester** [comment]
I generally think users _shouldn't_ have to know about `remotes`, but I concede when installing devtools dependencies this can cause problems on Windows.

Perhaps we could do something to direct users to try `remotes` when this occurs...

**Comment by HenrikBengtsson** [comment]
> I generally think users _shouldn't_ have to know about `remotes`, ...

For all non-developers out there, the opposite argument applies too; "users _shouldn't_ have to know about `devtools`".

I'm voting with OP on this one, especially since 'remotes' is so much lighter on dependencies and much quicker to get going with.

My $.02

**Comment by hadley** [comment]
I think it's generally better to use `remotes::install_github()` rather than `devtools::install_github()`, but generally we've been moving away from mentioning dev install instructions in the README at all, because most people are not well served by installing the development version of a package.

I think plumbing up `devtools::install_github()` to produce a useful error message would be hard it's just a re-exported `remotes::install_github()`, so we'd have to do some magic to figure where it was actually called from. This seems not so worthwhile since we're in the process of slowly moving away from remotes in favour of [pak](https://pak.r-lib.org) which takes a slightly different approach to resolving the dependency issue.
