### ISSUE TITLE
build_vignettes deletes Rmd files by default

### ISSUE THREAD

**Issue by Carldeboer** [r-lib/devtools#2228]
Hi 
I noticed that devtools deletes the source `.Rmd` files from `vignettes/` by default. If you add `keep_md = TRUE` then it keeps the source `.Rmd` files in `vignettes/`, and also copies the `.Rmd` files to `doc/`.  Deleting the `.md` files by default makes sense when they are an intermediate file, but in this case they are the originals and cannot easily be reproduced by the output `.R` and `.html` products.  I would have thought that the default behavior would be to keep any source `.md` files (i.e. not intermediates).

**Comment by hadley** [comment]
I just ran `build_vignettes()` on devtools itself and it didn't delete devtools one vignette. So you're going to need to provide a reprex with more details.

**Comment by stefanoborini** [comment]
I am experiencing the same problem.

**Comment by hadley** [comment]
I'd suggest filing a new issue with a reprex.

**Comment by stefanoborini** [comment]
@hadley we can't. Because it's a hard to track down bug. Stop asking for reproducible examples and try to take a look at the code to see if the situation can occur from the glimpses that the users give you. We are trying to fix your application, but we are not magicians. We see a behavior, you have two users that experience the exact same behavior, so it is not a fluke. See how possible it is and start a conversation.

What I have seen, is that it tends to happen when I have the vignettes build in progress, and I am also modifying the vignette file while it's being built. You have a chunk of code that is doing deletion of md files. Is it possible that something that is not a plain .md file with extension is added to that list of removals? 

```
> devtools:::copy_vignettes 
function (pkg, keep_md) 
{
    pkg <- as.package(pkg)
    usethis_use_directory(pkg, "doc", ignore = TRUE)
    usethis_use_git_ignore(pkg, "doc")
    doc_dir <- file.path(pkg$path, "doc")
    vigns <- tools::pkgVignettes(dir = pkg$path, output = TRUE, 
        source = TRUE)
    if (length(vigns$docs) == 0) 
        return(invisible())
    md_outputs <- character()
    if (isTRUE(keep_md)) {
        md_outputs <- list.files(path = vigns$dir, pattern = "[.]md$", 
            full.names = TRUE)
    }
    out_mv <- c(md_outputs, vigns$outputs, unique(unlist(vigns$sources, 
        use.names = FALSE)))
    out_cp <- vigns$docs
    message("Moving ", paste(basename(out_mv), collapse = ", "), 
        " to doc/")
    file.copy(out_mv, doc_dir, overwrite = TRUE)
    file.remove(out_mv)
    message("Copying ", paste(basename(out_cp), collapse = ", "), 
        " to doc/")
    file.copy(out_cp, doc_dir, overwrite = TRUE)
    extra_files <- find_vignette_extras(pkg)
    if (length(extra_files) == 0) 
        return(invisible())
    message("Copying extra files ", paste(basename(extra_files), 
        collapse = ", "), " to doc/")
    file.copy(extra_files, doc_dir, recursive = TRUE)
    invisible()
}
```

Besides, I think it's general poor practice to have the built files in the same directory as the live files, exactly because you have to keep track of them. Creating a separate directory and working inside that is safer.

**Comment by malcolmbarrett** [comment]
＠stefanoborini I don't know if this will fix your issue, but I can tell from the code you pasted that you're using an old version of devtools. Try installing the latest dev version and see if that helps.

**Comment by stefanoborini** [comment]
@malcolmbarrett same issue. I have seen timestamp files being created. I suspect what's happening is that every file younger than the timestamp is deleted, which includes a recently modified .Rmd.

**Comment by hadley** [comment]
@stefanoborini without any details of precisely what you're doing, there's little hope of finding and fixing the problem. Me and my team are collectively responsible for thousands of issues across hundreds of repos, and we need to prioritise our time carefully. In this case, we have a bug that only appears to affect two people in two years and neither of those people seem interested in giving us the details to track down the problem. If you want to persuade us to look into your problem in more detail, I'd suggest supplying a reprex and trying to be a little more cordial when asking for help.

**Comment by stefanoborini** [comment]
@hadley and I suggest you take more seriously the bug reports from your paying customers.

**Comment by hadley** [comment]
Of course your bug reports are taken very seriously for the products that you pay for, but as fa I'm aware you're not paying for our open source products and you don't have a support license for them. Please correct me if I'm wrong.
