### ISSUE TITLE
more meaningful error message for install_github() when branch master doesn't exist

### ISSUE THREAD

**Issue by myoung3** [r-lib/devtools#2237]
github is planning on "master" no longer being the default branch.

If you try to install_github() from a repo that doesn't have a master branch, you get this error message:

```
Downloading GitHub repo <user>/<repo>@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/<user>/<repo>/tarball/master'
```
While the message does contain `@master` which hints at the issue, it still could be more clear. Maybe add something like, "Perhaps this repo uses a different name for the main branch?"

**Comment by gaborcsardi** [comment]
This error is not thrown by devtools or remotes, but `utils::download.file()`. So we would need to catch it and somehow deduce that it happened because the branch does not exist. Which is challenging, because you get the same exact HTTP 404 error if (say) the user does not exist, or if repo is private and you have no access to it, etc.

Given that devtools/remotes will install the default branch soon (https://github.com/r-lib/remotes/pull/510), I am not sure if this needs fixing. An error message that points to the wrong thing is probably worse than a generic "url not found" error message.

**Comment by myoung3** [comment]
You're right this is more an issue of "master" being hardcoded as the default in install_github() rather than the error message itself. So changing the default branch from "master" to HEAD absolutely fixes this problem.

**Comment by NathanSkene** [comment]
This problem has wasted a good chunk of my time and seems to me that it should be fixed. Have heard of numerous others having the issue as well.

**Comment by jimhester** [comment]
@NathanSkene it is already fixed, please update your version of the remotes package.
