### ISSUE TITLE
I can't install devtools package in R

### ISSUE THREAD

**Issue by Nachoeigu** [r-lib/devtools#2338]
Hi everyone, I want to download the devtool package but I have this problem. Could someone help me?

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
also installing the dependency ‘pkgload’

  There are binary versions available but the source versions are later:
         binary source needs_compilation
pkgload   1.2.0  1.2.1              TRUE
devtools  2.3.2  2.4.0             FALSE

  Binaries will be installed
trying URL 'http://cran.rstudio.com/bin/windows/contrib/4.0/pkgload_1.2.0.zip'
Content type 'application/zip' length 152411 bytes (148 KB)
downloaded 148 KB

package ‘pkgload’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Sol\AppData\Local\Temp\RtmpGcx1vO\downloaded_packages
installing the source package ‘devtools’

trying URL 'http://cran.rstudio.com/src/contrib/devtools_2.4.0.tar.gz'
Content type 'application/x-gzip' length 369987 bytes (361 KB)
downloaded 361 KB

* installing *source* package 'devtools' ...
** package 'devtools' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning message:
package 'usethis' was built under R version 4.0.4 
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'pkgload' 1.2.0 is being loaded, but >= 1.2.1 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'devtools'
* removing 'C:/Users/Sol/Desktop/R/R-4.0.3/library/devtools'
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Sol\AppData\Local\Temp\RtmpGcx1vO\downloaded_packages’

**Comment by jimhester** [comment]
devtools and pkgload were recently released to CRAN and binaries are not yet available, so you need [Rtools](https://rstats.wtf/set-up-an-r-dev-environment.html) installed in order to install the source packages.

There is nothing wrong with the devtools package, so I am going to close this issue.

If you have further questions on figuaring Rtools or installing recently released packages please ask them on <https://community.rstudio.com>, in general it is a better avenue for help with installation problems them opening issues on devtools.
