### ISSUE TITLE
`devtools::dev_sitrep()` failing on Windows system

### ISSUE THREAD

**Issue by jacobspangler-agendia** [r-lib/devtools#2434]
When I use the `devtools::dev_sitrep()` function, I'm getting a 400 bad request response:

> Error in utils::download.file(url, tmp, quiet = TRUE) :
> cannot open URL 'https://www.rstudio.org/links/check_for_update?version=2022.2.2.485&os=windows&format=kvp'
> In addition: Warning message:
> In utils::download.file(url, tmp, quiet = TRUE) :
> cannot open URL 'https://www.rstudio.org/links/check_for_update?version=2022.2.2.485&os=windows&format=kvp': HTTP status was '400 Bad Request'

This appears similar to issue [2397](https://github.com/r-lib/devtools/issues/2397)

**Comment by jennybc** [comment]
@jgutman does the above surprise you?

**Comment by jennybc** [comment]
I definitely get the same 400:

``` r
httr::GET("https://www.rstudio.org/links/check_for_update?version=2022.2.2.485&os=windows&format=kvp")
#> Response [https://www.rstudio.org/links/check_for_update?version=2022.2.2.485&os=windows&format=kvp]
#>   Date: 2022-06-02 22:41
#>   Status: 400
#>   Content-Type: text/html; charset=UTF-8
#> <EMPTY BODY>
```

so the question really is ... is devtools making a bad URL or does some URL that should work, not working?

**Comment by jennybc** [comment]
I wonder if this particular build (`2022.2.2.485`) was removed or de-listed as part of the response to this:

> PSA: If you're using [@RStudio](https://twitter.com/rstudio) with R 4.2 on Windows, please update to the just-released 2022.02.3. There's an issue with R 4.2 and older [@RStudio](https://twitter.com/rstudio) releases that can empty your R scripts

https://twitter.com/rstudiotips/status/1532775784632356865

**Comment by jgutman** [comment]
No, we literally just released that patch, so that isn't the reason. I will be evaluating this, its just been busy this week

**Comment by jgutman** [comment]
Okay, so I have identified the issue, and it does appear that the correct URL is not being formed. IIRC, the PR we had previously discussed, the intended approach was to call `rstudioapi::versionInfo()$long_version` and use the long version in constructing the URL. Because some older versions of RStudio do not have a long version, if there was no long version, fall back to the `rstudioapi::versionInfo()$version`. For the identified version, the long version is `2022.02.2+485`, and we should be using the escaped long version, rather than the (short) `version`, which is `2022.2.2.485` and does not exist on the page. I'm not sure offhand why it is using the version rather than the long version, but I believe that is the source of the error

**Comment by jgutman** [comment]
@jacobspangler-agendia do you get the same error with the latest development version of `devtools` from Github? It seems like this fails using the version of devtools on CRAN, but passes if I install from Github.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/7817881/171959829-6465cce8-ca3e-4414-8fde-776a495d0e35.png">

**Comment by jennybc** [comment]
Ah, yes. I haven't released devtools to CRAN since implementing the fix for this function!

https://github.com/r-lib/devtools/blob/main/NEWS.md#devtools-development-version
