### ISSUE TITLE
[BUG] Issue in document(): Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.

### ISSUE THREAD

**Issue by jmrothen** [r-lib/devtools#2512]
**Is your feature request related to a problem? Please describe.**
When creating the documentation for a new project of mine, I keep running into the following error when attempting to view the .Rd files in the man folder;

ℹ Rendering development documentation for "function_name_here"
Error in .get_package_metadata(pkgdir) : 
  Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.

**Describe the solution you'd like**
I imagine this is a new bug as of R 4.3.0 (which I am currently using). There is a DESCRIPTION file in the project, which has been created by the docu

**Additional context**
R 4.3.0 
devtools 2.4.5

**Comment by jmrothen** [comment]
deleted description file, went back and rewrote all my roxygen chunks, and then was able to get everything to work correctly after a devtools::document()

**Comment by shirewoman2** [comment]
I'm having the same issue. When you say that you "rewrote" all the roxygen chunks, how did you go about doing that? Manually?

**Comment by shirewoman2** [comment]
Thanks! I really appreciate the example! I don't see any obvious differences between your DESCRIPTION file and mine or between how you have set up the man pages. I did find that a one-off error I was seeing was due to having a carriage return between @export and @examples on one of the package functions because it went away when I deleted that. (I had export and then examples; I see you've got examples and then export, but I don't think that should matter.) Here's the repo for my [package](https://github.com/shirewoman2/Consultancy/tree/master).
