### ISSUE TITLE
release function error

### ISSUE THREAD

**Issue by sckott** [r-lib/devtools#379]
`release` is giving errors on my machine since I updated my OSX os to Mavericks, e.g, 

``` coffee
release(pkgname)
...
Checking pkgname with devtools
Checking for any extra files in built .tar.gz file... sh: /usr/bin/gnutar: No such file or directory
Error in system(cmd, intern = TRUE) : error in running command
```

This error doesn't happen with `R CMD CHECK` or `R CMD BUILD`

My setup:
-OSX 10.9
-R 3.0.2

On twitter you asked if I was using the latest version of R, does that mean dev or stable?
I do have the latest devtools from Github, master branch.

**Comment by GISDev01** [comment]
For any future google'ers that end up here like I did, I actually had a similar issue with using devtools to install xml2 via the git repo. 

This is the command and the error I was getting on Ubuntu 14.04.5 on an AWS EC2 box running Anaconda r-essentials as the R 3.2.2 distro:
devtools::install_git("git://github.com/hadley/xml2.git", branch = "master")
Installing xml2
trying URL 'http://cran.rstudio.com/src/contrib/BH_1.60.0-2.tar.gz'
Content type 'application/x-gzip' length 9783419 bytes (9.3 MB)
==================================================
downloaded 9.3 MB
sh: 1: /bin/gtar: not found
 
**To fix it, I tried something similar to work worked for @sckott above:**
`sudo ln -s /bin/tar /bin/gtar`
Sure enough, symlinking gtar to the real tar did the trick, and the install went perfectly after that.  

Pretty sure this has nothing to do with any bugs in devtools or xml2, but something that is wacky with my PATH and Anaconda R having something up with it, but this did the trick for us.

**Comment by ressy** [comment]
Just to add a little more proof to what @GISDev01 mentioned (since I'm one of those future googlers), it's `Sys.getenv("TAR")` by way of `utils::untar` that's to blame, at least in my case.  That getenv call returns /bin/gtar on my system for some reason.  (This is all inside an Anaconda-provided R install; it returns the correct path when using the OS-provided R package.)

A simple fix that did the trick for me and doesn't require root access was just doing an `export TAR=/bin/tar` on the shell before launching R.  Then `Sys.getenv("TAR")` just returns the actual environment variable instead of doing whatever magic it does to try to figure it out, and devtools can untar its dependencies during installation.

**Comment by carbocation** [comment]
To make this even simpler for people with this issue, calling the following in R resolved this issue for me without having to exit R, change my path, sudo, etc:
```
Sys.setenv(TAR = "/bin/tar")
```
