### ISSUE TITLE
Starting package version should be 0.0.0.9000

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#632]

**Comment by sanmai-NL** [comment]
I would like to bring this issue up again. I do not see a very strong case to deviate the R versioning scheme from [Semantic Versioning 2.0.0](http://semver.org/), given that the [R-exts documentation](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file) seems compatible with this widely adopted standard. 

First of all, currently the initial version as prescribed in the [development guide](http://r-pkgs.had.co.nz/description.html) appears to be:
```
Version: 0.1
```

Although there is indeed a deviation between SemVer and R's treatment of
```R
package_version("0.1.0") < package_version("0.1.0-9000")
#> [1] TRUE
```
This can be easily circumvented using a default initial version of
```R
package_version("0.1.0-2") < package_version("0.1.0-1")
#> [1] FALSE
```

@hadley, you wrote at the time that SemVer is only for released versions. However, SemVer 2.0.0 states: 
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I don't believe that R versioning must necessarily be out of step with conventions for general purpose programming languages. For e.g. Python, [some deviation](http://docs.openstack.org/developer/pbr/semver.html) happens for [PEP 0440](https://www.python.org/dev/peps/pep-0440) compliance. But if there is a lack of such a standardized convention in R, then I would suggest that the example `DESCRIPTION` and `devtools` take the SemVer compatible default of `0.1.0` instead of `0.1`.

The practical **benefit**: such an improvement allows you to refer your readership and user base to SemVer, if they want to come to understand the logic of software versioning, even if they are R package developers not familiar with software engineering practices. That would encourage good package development practices, e.g. understanding the difference between essential quality levels of software and how to communicate them.
